// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechSupportSystemWeb.Data;

#nullable disable

namespace TechSupportSystemWeb.Migrations
{
    [DbContext(typeof(SupportSystemDbContext))]
    partial class SupportSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("SupportTicketTechnician", b =>
                {
                    b.Property<int>("TechniciansID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketsID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TechniciansID", "TicketsID");

                    b.HasIndex("TicketsID");

                    b.ToTable("SupportTicketTechnician");
                });

            modelBuilder.Entity("TechSupportSystemWeb.Models.SupportNote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupportTicketID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SupportTicketID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("TechSupportSystemWeb.Models.SupportTicket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TechSupportSystemWeb.Models.Technician", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("SupportTicketTechnician", b =>
                {
                    b.HasOne("TechSupportSystemWeb.Models.Technician", null)
                        .WithMany()
                        .HasForeignKey("TechniciansID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechSupportSystemWeb.Models.SupportTicket", null)
                        .WithMany()
                        .HasForeignKey("TicketsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechSupportSystemWeb.Models.SupportNote", b =>
                {
                    b.HasOne("TechSupportSystemWeb.Models.SupportTicket", null)
                        .WithMany("Notes")
                        .HasForeignKey("SupportTicketID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TechSupportSystemWeb.Models.SupportTicket", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
